#ifndef __RWLAPACK_H__
#define __RWLAPACK_H__

/*
 * Prototypes for the lapack source.
 *
 * $$RW_INSERT_HEADER "mathyrs.str"
 *
 * Prototypes built using Cobalt Blue's FOR_C++ v1.1 (P) Fortran to C
 * translator, and then hand massaged to fit the Rogue Wave guidelines
 * for lapack.h++.  The original Cobalt Blue generated header files have
 * been retained ([xsdcz]lapack.h) to allow future translation of Fortran
 * files that use these functions.
 *
 */

#include "rw/lapkdefs.h"

/*
 * Need to actually include dcomplex.h --- since DComplex may just
 * be a typedef we can't just forward declare it as a class.
 */
#include "rw/mathdefs.h"
#include "rw/dcomplex.h"
#if defined(__GNUC__)
typedef std::complex<float> FComplex;
#else
class FComplex;
#endif

/*
 * The RWBLADECL macro is set in mathdefs.h for versions of math.h++ higher
 * than 5.0.0.  We set it here in case this is math.h++ 5.0.0 and it has
 * not been redefined in mathdefs.h already
 */
#if RWMATH<=0x500 && !defined(RWLAPKDECL)
#define RWLAPKDECL extern "C"
#endif

RWLAPKDECL long     icmax1(const long&,FComplex[],const long&);
RWLAPKDECL long     ilaenv(const long&,char*,char*,const long&,const long&,const long&,const long&);
RWLAPKDECL long     izmax1(const long&,DComplex[],const long&);
RWLAPKDECL int      lsame(const char&,const char&);
RWLAPKDECL int      lsamen(const long&, char *s1, int s1len, char *s2, int s2len);
RWLAPKDECL void     xerbla(char*,const long&);

RWLAPKDECL void     dbdsqr(const char&,const long&,const long&,const long&,const long&,double[],double[],double*,const long&,double*,const long&,double*,const long&,double[],long&);
RWLAPKDECL void     dgbcon(const char&,long&,long&,long&,double*,long&,long[],double&,double&,double[],long[],long&);
RWLAPKDECL void     dgbequ(const long&,const long&,const long&,const long&,double*,const long&,double[],double[],double&,double&,double&,long&);
RWLAPKDECL void     dgbrfs(const char&,const long&,const long&,const long&,const long&,double*,const long&,double*,const long&,long[],double*,const long&,double*,const long&,double[],double[],double[],long[],long&);
RWLAPKDECL void     dgbsv(const long&,const long&,const long&,const long&,double*,const long&,long[],double*,const long&,long&);
RWLAPKDECL void     dgbsvx(const char&,const char&,long&,long&,long&,long&,double*,long&,double*,long&,long[],char&,double[],double[],double*,long&,double*,long&,double&,double[],double[],double[],long[],long&);
RWLAPKDECL void     dgbtf2(const long&,const long&,const long&,const long&,double*,const long&,long[],long&);
RWLAPKDECL void     dgbtrf(const long&,const long&,const long&,const long&,double*,const long&,long[],long&);
RWLAPKDECL void     dgbtrs(const char&,const long&,const long&,const long&,const long&,double*,const long&,long[],double*,const long&,long&);
RWLAPKDECL void     dgebak(const char&,const char&,const long&,const long&,const long&,double[],const long&,double*,const long&,long&);
RWLAPKDECL void     dgebal(const char&,const long&,double*,const long&,long&,long&,double[],long&);
RWLAPKDECL void     dgebd2(const long&,const long&,double*,const long&,double[],double[],double[],double[],double[],long&);
RWLAPKDECL void     dgebrd(const long&,const long&,double*,const long&,double[],double[],double[],double[],double[],const long&,long&);
RWLAPKDECL void rwlapkfuncexport     dgecon(const char&,long&,double*,long&,double&,double&,double[],long[],long&);
RWLAPKDECL void     dgeequ(const long&,const long&,double*,const long&,double[],double[],double&,double&,double&,long&);
RWLAPKDECL void     dgees(const char&,const char&,int(*select)(double[],double[]),const long&,double*,const long&,const long&,double[],double[],double*,const long&,double[],const long&,int[],long&);
RWLAPKDECL void     dgeesx(const char&,const char&,int(*select)(double[],double[]),const char&,const long&,double*,const long&,const long&,double[],double[],double*,const long&,const double&,const double&,double[],const long&,long[],const long&,int[],long&);
RWLAPKDECL void     dgeev(const char&,const char&,const long&,double*,const long&,double[],double[],double*,const long&,double*,const long&,double[],const long&,long&);
RWLAPKDECL void     dgeevx(const char&,const char&,const char&,const char&,long&,double*,long&,double[],double[],double*,long&,double*,long&,long&,long&,double[],double&,double[],double[],double[],long&,long[],long&);
RWLAPKDECL void     dgehd2(const long&,const long&,const long&,double*,const long&,double[],double[],long&);
RWLAPKDECL void     dgehrd(const long&,const long&,const long&,double*,const long&,double[],double[],const long&,long&);
RWLAPKDECL void     dgelq2(const long&,const long&,double*,const long&,double[],double[],long&);
RWLAPKDECL void     dgelqf(const long&,const long&,double*,const long&,double[],double[],const long&,long&);
RWLAPKDECL void     dgels(const char&,const long&,const long&,const long&,double*,const long&,double*,const long&,double[],const long&,long&);
RWLAPKDECL void     dgelss(const long&,const long&,const long&,double*,const long&,double*,const long&,double[],double&,long&,double[],long&,long&);
RWLAPKDECL void     dgelsx(const long&,const long&,const long&,double*,const long&,double*,const long&,long[],const double&,long&,double[],long&);
RWLAPKDECL void     dgeql2(const long&,const long&,double*,const long&,double[],double[],long&);
RWLAPKDECL void     dgeqlf(const long&,const long&,double*,const long&,double[],double[],const long&,long&);
RWLAPKDECL void     dgeqpf(const long&,const long&,double*,const long&,long[],double[],double[],long&);
RWLAPKDECL void     dgeqr2(const long&,const long&,double*,const long&,double[],double[],long&);
RWLAPKDECL void     dgeqrf(const long&,const long&,double*,const long&,double[],double[],const long&,long&);
RWLAPKDECL void     dgerfs(const char&,const long&,const long&,double*,const long&,double*,const long&,long[],double*,const long&,double*,const long&,double[],double[],double[],long[],long&);
RWLAPKDECL void     dgerq2(const long&,const long&,double*,const long&,double[],double[],long&);
RWLAPKDECL void     dgerqf(const long&,const long&,double*,const long&,double[],double[],const long&,long&);
RWLAPKDECL void     dgesv(const long&,const long&,double*,const long&,long[],double*,const long&,long&);
RWLAPKDECL void     dgesvd(const char&,const char&,const long&,const long&,double*,const long&,double[],double*,const long&,double*,const long&,double[],const long&,long&);
RWLAPKDECL void     dgesvx(const char&,const char&,long&,long&,double*,long&,double*,long&,long[],char&,double[],double[],double*,long&,double*,long&,double&,double[],double[],double[],long[],long&);
RWLAPKDECL void     dgetf2(const long&,const long&,double*,const long&,long[],long&);
RWLAPKDECL void rwlapkfuncexport     dgetrf(const long&,const long&,double*,const long&,long[],long&);
RWLAPKDECL void rwlapkfuncexport    dgetri(const long&,double*,const long&,long[],double[],const long&,long&);
RWLAPKDECL void rwlapkfuncexport     dgetrs(const char&,const long&,const long&,double*,const long&,long[],double*,const long&,long&);
RWLAPKDECL void     dgtcon(const char&,long&,double[],double[],double[],double[],long[],double&,double&,double[],long[],long&);
RWLAPKDECL void     dgtrfs(const char&,const long&,const long&,double[],double[],double[],double[],double[],double[],double[],long[],double*,const long&,double*,const long&,double[],double[],double[],long[],long&);
RWLAPKDECL void     dgtsv(const long&,const long&,double[],double[],double[],double*,const long&,long&);
RWLAPKDECL void     dgtsvx(const char&,const char&,long&,long&,double[],double[],double[],double[],double[],double[],double[],long[],double*,long&,double*,long&,double&,double[],double[],double[],long[],long&);
RWLAPKDECL void     dgttrf(const long&,double[],double[],double[],double[],long[],long&);
RWLAPKDECL void     dgttrs(const char&,const long&,const long&,double[],double[],double[],double[],long[],double*,const long&,long&);
RWLAPKDECL void     dhsein(const char&,const char&,const char&,int[],long&,double*,long&,double[],double[],double*,long&,double*,long&,long&,long&,double[],long[],long[],long&);
RWLAPKDECL void     dhseqr(const char&,const char&,const long&,const long&,const long&,double*,const long&,double[],double[],double*,const long&,double[],const long&,long&);
RWLAPKDECL void     dlabad(double&,double&);
RWLAPKDECL void     dlabrd(const long&,const long&,const long&,double*,const long&,double[],double[],double[],double[],double*,const long&,double*,const long&);
RWLAPKDECL void     dlacon(const long&,double[],double[],long[],double&,long&);
RWLAPKDECL void     dlacpy(const char&,const long&,const long&,double*,const long&,double*,const long&);
RWLAPKDECL void     dladiv(const double&,const double&,const double&,const double&,double&,double&);
RWLAPKDECL void     dlae2(const double&,const double&,const double&,double&,double&);
RWLAPKDECL void     dlaebz(const long&,const long&,const long&,const long&,const long&,const long&,const double&,const double&,const double&,double[],double[],double[],long[],double*,double[],long&,long*,double[],long[],long&);
RWLAPKDECL void     dlaein(const int&,const int&,const long&,double*,const long&,const double&,const double&,double[],double[],double*,const long&,double[],const double&,const double&,const double&,long&);
RWLAPKDECL void     dlaev2(const double&,const double&,const double&,double&,double&,double&,double&);
RWLAPKDECL void     dlaexc(const int&,const long&,double*,const long&,double*,const long&,const long&,const long&,const long&,double[],long&);
RWLAPKDECL void     dlagtf(const long&,double[],const double&,double[],double[],const double&,double[],long[],long&);
RWLAPKDECL void     dlagtm(const char&,const long&,const long&,const double&,double[],double[],double[],double*,const long&,const double&,double*,const long&);
RWLAPKDECL void     dlagts(const long&,const long&,double[],double[],double[],double[],long[],double[],double&,long&);
RWLAPKDECL void     dlahqr(const int&,const int&,const long&,const long&,const long&,double*,const long&,double[],double[],const long&,const long&,double*,const long&,long&);
RWLAPKDECL void     dlahrd(const long&,const long&,const long&,double*,const long&,double[],double*,const long&,double*,const long&);
RWLAPKDECL void     dlaic1(const long&,const long&,double[],const double&,double[],const double&,double&,double&,double&);
RWLAPKDECL void     dlaln2(const int&,const long&,const long&,const double&,const double&,double*,const long&,const double&,const double&,double*,const long&,const double&,const double&,double*,const long&,double&,double&,long&);
RWLAPKDECL double   dlamch(const char&);
RWLAPKDECL double   dlangb(const char&,const long&,const long&,const long&,double*,const long&,double[]);
RWLAPKDECL double rwlapkfuncexport   dlange(const char&,const long&,const long&,double*,const long&,double[]);
RWLAPKDECL double   dlangt(const char&,const long&,double[],double[],double[]);
RWLAPKDECL double   dlanhs(const char&,const long&,double*,const long&,double[]);
RWLAPKDECL double   dlansb(const char&,const char&,const long&,const long&,double*,const long&,double[]);
RWLAPKDECL double   dlansp(const char&,const char&,const long&,double[],double[]);
RWLAPKDECL double   dlanst(const char&,const long&,double[],double[]);
RWLAPKDECL double   dlansy(const char&,const char&,const long&,double*,const long&,double[]);
RWLAPKDECL double   dlantb(const char&,const char&,const char&,const long&,const long&,double*,const long&,double[]);
RWLAPKDECL double   dlantp(const char&,const char&,const char&,const long&,double[],double[]);
RWLAPKDECL double   dlantr(const char&,const char&,const char&,const long&,const long&,double*,const long&,double[]);
RWLAPKDECL void     dlanv2(double&,double&,double&,double&,double&,double&,double&,double&,double&,double&);
RWLAPKDECL double   dlapy2(const double&,const double&);
RWLAPKDECL double   dlapy3(const double&,const double&,const double&);
RWLAPKDECL void     dlaqgb(const long&,const long&,const long&,const long&,double*,const long&,double[],double[],double&,double&,double&,char&);
RWLAPKDECL void     dlaqge(const long&,const long&,double*,const long&,double[],double[],double&,double&,double&,char&);
RWLAPKDECL void     dlaqsb(const char&,long&,long&,double*,long&,double[],double&,double&,char&);
RWLAPKDECL void     dlaqsp(const char&,long&,double[],double[],double&,double&,char&);
RWLAPKDECL void     dlaqsy(const char&,long&,double*,long&,double[],double&,double&,char&);
RWLAPKDECL void     dlaqtr(const int&,const int&,const long&,double*,const long&,double[],const double&,double&,double[],double[],long&);
RWLAPKDECL void     dlar2v(const long&,double[],double[],double[],const long&,double[],double[],const long&);
RWLAPKDECL void     dlarf(const char&,const long&,const long&,double[],const long&,const double&,double*,const long&,double[]);
RWLAPKDECL void     dlarfb(const char&,const char&,const char&,const char&,const long&,const long&,const long&,double*,const long&,double*,const long&,double*,const long&,double*,const long&);
RWLAPKDECL void     dlarfg(const long&,double&,double[],const long&,double&);
RWLAPKDECL void     dlarft(const char&,const char&,const long&,const long&,double*,const long&,double[],double*,const long&);
RWLAPKDECL void     dlarfx(const char&,const long&,const long&,double[],const double&,double*,const long&,double[]);
RWLAPKDECL void     dlargv(const long&,double[],const long&,double[],const long&,double[],const long&);
RWLAPKDECL void     dlarnv(const long&,long[],const long&,double[]);
RWLAPKDECL void     dlartg(const double&,const double&,double&,double&,double&);
RWLAPKDECL void     dlartv(const long&,double[],const long&,double[],const long&,double[],double[],const long&);
RWLAPKDECL void     dlaruv(long[],const long&,double[]);
RWLAPKDECL void     dlas2(const double&,const double&,const double&,double&,double&);
RWLAPKDECL void     dlascl(const char&,const long&,const long&,const double&,const double&,const long&,const long&,double*,const long&,long&);
RWLAPKDECL void     dlaset(const char&,const long&,const long&,const double&,const double&,double*,const long&);
RWLAPKDECL void     dlasr(const char&,const char&,const char&,const long&,const long&,double[],double[],double*,const long&);
RWLAPKDECL void     dlassq(const long&,double[],const long&,double&,double&);
RWLAPKDECL void     dlasv2(const double&,const double&,const double&,double&,double&,double&,double&,double&,double&);
RWLAPKDECL void     dlaswp(const long&,double*,const long&,const long&,const long&,long[],const long&);
RWLAPKDECL void     dlasy2(const int&,const int&,const long&,const long&,const long&,double*,const long&,double*,const long&,double*,const long&,double&,double*,const long&,double&,long&);
RWLAPKDECL void     dlasyf(const char&,const long&,const long&,long&,double*,const long&,long[],double*,const long&,long&);
RWLAPKDECL void     dlatbs(const char&,const char&,const char&,const char&,const long&,const long&,double*,const long&,double[],double&,double[],long&);
RWLAPKDECL void     dlatps(const char&,const char&,const char&,const char&,long&,double[],double[],double&,double[],long&);
RWLAPKDECL void     dlatrd(const char&,const long&,const long&,double*,const long&,double[],double[],double*,const long&);
RWLAPKDECL void     dlatrs(const char&,const char&,const char&,const char&,const long&,double*,const long&,double[],double&,double[],long&);
RWLAPKDECL void     dlatzm(const char&,const long&,const long&,double[],const long&,const double&,double*,double*,const long&,double[]);
RWLAPKDECL void     dlauu2(const char&,const long&,double*,const long&,long&);
RWLAPKDECL void     dlauum(const char&,const long&,double*,const long&,long&);
RWLAPKDECL void     dlazro(const long&,const long&,const double&,const double&,double*,const long&);
RWLAPKDECL void     dopgtr(const char&,const long&,double[],double[],double*,const long&,double[],long&);
RWLAPKDECL void     dopmtr(const char&,const char&,const char&,const long&,const long&,double[],double[],double*,const long&,double[],long&);
RWLAPKDECL void     dorg2l(const long&,const long&,const long&,double*,const long&,double[],double[],long&);
RWLAPKDECL void     dorg2r(const long&,const long&,const long&,double*,const long&,double[],double[],long&);
RWLAPKDECL void     dorgbr(const char&,const long&,const long&,const long&,double*,const long&,double[],double[],const long&,long&);
RWLAPKDECL void     dorghr(const long&,const long&,const long&,double*,const long&,double[],double[],const long&,long&);
RWLAPKDECL void     dorgl2(const long&,const long&,const long&,double*,const long&,double[],double[],long&);
RWLAPKDECL void     dorglq(const long&,const long&,const long&,double*,const long&,double[],double[],const long&,long&);
RWLAPKDECL void     dorgql(const long&,const long&,const long&,double*,const long&,double[],double[],const long&,long&);
RWLAPKDECL void     dorgqr(const long&,const long&,const long&,double*,const long&,double[],double[],const long&,long&);
RWLAPKDECL void     dorgr2(const long&,const long&,const long&,double*,const long&,double[],double[],long&);
RWLAPKDECL void     dorgrq(const long&,const long&,const long&,double*,const long&,double[],double[],const long&,long&);
RWLAPKDECL void     dorgtr(const char&,const long&,double*,const long&,double[],double[],const long&,long&);
RWLAPKDECL void     dorm2l(const char&,const char&,const long&,const long&,const long&,double*,const long&,double[],double*,const long&,double[],long&);
RWLAPKDECL void     dorm2r(const char&,const char&,const long&,const long&,const long&,double*,const long&,double[],double*,const long&,double[],long&);
RWLAPKDECL void     dormbr(const char&,const char&,const char&,const long&,const long&,const long&,double*,const long&,double[],double*,const long&,double[],const long&,long&);
RWLAPKDECL void     dormhr(const char&,const char&,const long&,const long&,const long&,const long&,double*,const long&,double[],double*,const long&,double[],const long&,long&);
RWLAPKDECL void     dorml2(const char&,const char&,const long&,const long&,const long&,double*,const long&,double[],double*,const long&,double[],long&);
RWLAPKDECL void     dormlq(const char&,const char&,const long&,const long&,const long&,double*,const long&,double[],double*,const long&,double[],const long&,long&);
RWLAPKDECL void     dormql(const char&,const char&,const long&,const long&,const long&,double*,const long&,double[],double*,const long&,double[],const long&,long&);
RWLAPKDECL void     dormqr(const char&,const char&,const long&,const long&,const long&,double*,const long&,double[],double*,const long&,double[],const long&,long&);
RWLAPKDECL void     dormr2(const char&,const char&,const long&,const long&,const long&,double*,const long&,double[],double*,const long&,double[],long&);
RWLAPKDECL void     dormrq(const char&,const char&,const long&,const long&,const long&,double*,const long&,double[],double*,const long&,double[],const long&,long&);
RWLAPKDECL void     dormtr(const char&,const char&,const char&,const long&,const long&,double*,const long&,double[],double*,const long&,double[],const long&,long&);
RWLAPKDECL void     dpbcon(const char&,long&,long&,double*,long&,double&,double&,double[],long[],long&);
RWLAPKDECL void     dpbequ(const char&,long&,long&,double*,long&,double[],double&,double&,long&);
RWLAPKDECL void     dpbrfs(const char&,const long&,const long&,const long&,double*,const long&,double*,const long&,double*,const long&,double*,const long&,double[],double[],double[],long[],long&);
RWLAPKDECL void     dpbsv(const char&,const long&,const long&,const long&,double*,const long&,double*,const long&,long&);
RWLAPKDECL void     dpbsvx(const char&,const char&,long&,long&,long&,double*,long&,double*,long&,char&,double[],double*,long&,double*,long&,double&,double[],double[],double[],long[],long&);
RWLAPKDECL void     dpbtf2(const char&,const long&,const long&,double*,const long&,long&);
RWLAPKDECL void     dpbtrf(const char&,const long&,const long&,double*,const long&,long&);
RWLAPKDECL void     dpbtrs(const char&,const long&,const long&,const long&,double*,const long&,double*,const long&,long&);
RWLAPKDECL void     dpocon(const char&,long&,double*,long&,double&,double&,double[],long[],long&);
RWLAPKDECL void     dpoequ(const long&,double*,const long&,double[],double&,double&,long&);
RWLAPKDECL void     dporfs(const char&,const long&,const long&,double*,const long&,double*,const long&,double*,const long&,double*,const long&,double[],double[],double[],long[],long&);
RWLAPKDECL void     dposv(const char&,const long&,const long&,double*,const long&,double*,const long&,long&);
RWLAPKDECL void     dposvx(const char&,const char&,long&,long&,double*,long&,double*,long&,char&,double[],double*,long&,double*,long&,double&,double[],double[],double[],long[],long&);
RWLAPKDECL void     dpotf2(const char&,const long&,double*,const long&,long&);
RWLAPKDECL void     dpotrf(const char&,const long&,double*,const long&,long&);
RWLAPKDECL void     dpotri(const char&,const long&,double*,const long&,long&);
RWLAPKDECL void     dpotrs(const char&,const long&,const long&,double*,const long&,double*,const long&,long&);
RWLAPKDECL void     dppcon(const char&,long&,double[],double&,double&,double[],long[],long&);
RWLAPKDECL void     dppequ(const char&,long&,double[],double[],double&,double&,long&);
RWLAPKDECL void     dpprfs(const char&,const long&,const long&,double[],double[],double*,const long&,double*,const long&,double[],double[],double[],long[],long&);
RWLAPKDECL void     dppsv(const char&,const long&,const long&,double[],double*,const long&,long&);
RWLAPKDECL void     dppsvx(const char&,const char&,long&,long&,double[],double[],char&,double[],double*,long&,double*,long&,double&,double[],double[],double[],long[],long&);
RWLAPKDECL void     dpptrf(const char&,const long&,double[],long&);
RWLAPKDECL void     dpptri(const char&,const long&,double[],long&);
RWLAPKDECL void     dpptrs(const char&,const long&,const long&,double[],double*,const long&,long&);
RWLAPKDECL void     dptcon(const long&,double[],double[],const double&,double&,double[],long&);
RWLAPKDECL void     dpteqr(const char&,const long&,double[],double[],double*,const long&,double[],long&);
RWLAPKDECL void     dptrfs(const long&,const long&,double[],double[],double[],double[],double*,const long&,double*,const long&,double[],double[],double[],long&);
RWLAPKDECL void     dptsv(const long&,const long&,double[],double[],double*,const long&,long&);
RWLAPKDECL void     dptsvx(const char&,long&,long&,double[],double[],double[],double[],double*,long&,double*,long&,double&,double[],double[],double[],long&);
RWLAPKDECL void     dpttrf(const long&,double[],double[],long&);
RWLAPKDECL void     dpttrs(const long&,const long&,double[],double[],double*,const long&,long&);
RWLAPKDECL void     drscl(const long&,const double&,double[],const long&);
RWLAPKDECL void     dsbev(const char&,const char&,const long&,const long&,double*,const long&,double[],double*,const long&,double[],long&);
RWLAPKDECL void     dsbevx(const char&,const char&,const char&,long&,long&,double*,long&,double*,long&,double&,double&,long&,long&,double&,long&,double[],double*,long&,double[],long[],long[],long&);
RWLAPKDECL void     dsbtrd(const char&,const char&,const long&,const long&,double*,const long&,double[],double[],double*,const long&,double[],long&);
RWLAPKDECL double   dsecnd();
RWLAPKDECL void     dspcon(const char&,long&,double[],long[],double&,double&,double[],long[],long&);
RWLAPKDECL void     dspev(const char&,const char&,const long&,double[],double[],double*,const long&,double[],long&);
RWLAPKDECL void     dspevx(const char&,const char&,const char&,long&,double[],double&,double&,long&,long&,double&,long&,double[],double*,long&,double[],long[],long[],long&);
RWLAPKDECL void     dspgst(const long&,const char&,const long&,double[],double[],long&);
RWLAPKDECL void     dspgv(const long&,const char&,const char&,const long&,double[],double[],double[],double*,const long&,double[],long&);
RWLAPKDECL void     dsprfs(const char&,const long&,const long&,double[],double[],long[],double*,const long&,double*,const long&,double[],double[],double[],long[],long&);
RWLAPKDECL void     dspsv(const char&,const long&,const long&,double[],long[],double*,const long&,long&);
RWLAPKDECL void     dspsvx(const char&,const char&,long&,long&,double[],double[],long[],double*,long&,double*,long&,double&,double[],double[],double[],long[],long&);
RWLAPKDECL void     dsptrd(const char&,const long&,double[],double[],double[],double[],long&);
RWLAPKDECL void     dsptrf(const char&,const long&,double[],long[],long&);
RWLAPKDECL void     dsptri(const char&,const long&,double[],long[],double[],long&);
RWLAPKDECL void     dsptrs(const char&,const long&,const long&,double[],long[],double*,const long&,long&);
RWLAPKDECL void     dstebz(const char&,const char&,const long&,const double&,const double&,const long&,const long&,const double&,double[],double[],long&,long&,double[],long[],long[],double[],long[],long&);
RWLAPKDECL void     dstein(const long&,double[],double[],const long&,double[],long[],long[],double*,const long&,double[],long[],long[],long&);
RWLAPKDECL void     dsteqr(const char&,const long&,double[],double[],double*,const long&,double[],long&);
RWLAPKDECL void     dsterf(const long&,double[],double[],long&);
RWLAPKDECL void     dstev(const char&,const long&,double[],double[],double*,const long&,double[],long&);
RWLAPKDECL void     dstevx(const char&,const char&,long&,double[],double[],double&,double&,long&,long&,double&,long&,double[],double*,long&,double[],long[],long[],long&);
RWLAPKDECL void     dsycon(const char&,long&,double*,long&,long[],double&,double&,double[],long[],long&);
RWLAPKDECL void     dsyev(const char&,const char&,const long&,double*,const long&,double[],double[],const long&,long&);
RWLAPKDECL void     dsyevx(const char&,const char&,const char&,long&,double*,long&,double&,double&,long&,long&,double&,long&,double[],double*,long&,double[],long&,long[],long[],long&);
RWLAPKDECL void     dsygs2(const long&,const char&,const long&,double*,const long&,double*,const long&,long&);
RWLAPKDECL void     dsygst(const long&,const char&,const long&,double*,const long&,double*,const long&,long&);
RWLAPKDECL void     dsygv(const long&,const char&,const char&,const long&,double*,const long&,double*,const long&,double[],double[],const long&,long&);
RWLAPKDECL void     dsyrfs(const char&,const long&,const long&,double*,const long&,double*,const long&,long[],double*,const long&,double*,const long&,double[],double[],double[],long[],long&);
RWLAPKDECL void     dsysv(const char&,const long&,const long&,double*,const long&,long[],double*,const long&,double[],const long&,long&);
RWLAPKDECL void     dsysvx(const char&,const char&,long&,long&,double*,long&,double*,long&,long[],double*,long&,double*,long&,double&,double[],double[],double[],long&,long[],long&);
RWLAPKDECL void     dsytd2(const char&,const long&,double*,const long&,double[],double[],double[],long&);
RWLAPKDECL void     dsytf2(const char&,const long&,double*,const long&,long[],long&);
RWLAPKDECL void     dsytrd(const char&,const long&,double*,const long&,double[],double[],double[],double[],const long&,long&);
RWLAPKDECL void     dsytrf(const char&,const long&,double*,const long&,long[],double[],const long&,long&);
RWLAPKDECL void     dsytri(const char&,const long&,double*,const long&,long[],double[],long&);
RWLAPKDECL void     dsytrs(const char&,const long&,const long&,double*,const long&,long[],double*,const long&,long&);
RWLAPKDECL void     dtbcon(const char&,const char&,const char&,long&,long&,double*,long&,double&,double[],long[],long&);
RWLAPKDECL void     dtbrfs(const char&,const char&,const char&,const long&,const long&,const long&,double*,const long&,double*,const long&,double*,const long&,double[],double[],double[],long[],long&);
RWLAPKDECL void     dtbtrs(const char&,const char&,const char&,const long&,const long&,const long&,double*,const long&,double*,const long&,long&);
RWLAPKDECL void     dtpcon(const char&,const char&,const char&,long&,double[],double&,double[],long[],long&);
RWLAPKDECL void     dtprfs(const char&,const char&,const char&,const long&,const long&,double[],double*,const long&,double*,const long&,double[],double[],double[],long[],long&);
RWLAPKDECL void     dtptri(const char&,const char&,const long&,double[],long&);
RWLAPKDECL void     dtptrs(const char&,const char&,const char&,const long&,const long&,double[],double*,const long&,long&);
RWLAPKDECL void     dtrcon(const char&,const char&,const char&,long&,double*,long&,double&,double[],long[],long&);
RWLAPKDECL void     dtrevc(const char&,const char&,int[],const long&,double*,const long&,double*,const long&,double*,const long&,const long&,long&,double[],long&);
RWLAPKDECL void     dtrexc(const char&,const long&,double*,const long&,double*,const long&,long&,long&,double[],long&);
RWLAPKDECL void     dtrrfs(const char&,const char&,const char&,const long&,const long&,double*,const long&,double*,const long&,double*,const long&,double[],double[],double[],long[],long&);
RWLAPKDECL void     dtrsen(const char&,const char&,int[],long&,double*,long&,double*,long&,double[],double[],long&,double&,double&,double[],long&,long[],long&,long&);
RWLAPKDECL void     dtrsna(const char&,const char&,int[],long&,double*,long&,double*,long&,double*,long&,double[],double[],long&,long&,double*,long&,long[],long&);
RWLAPKDECL void     dtrsyl(const char&,const char&,const long&,const long&,const long&,double*,const long&,double*,const long&,double*,const long&,double&,long&);
RWLAPKDECL void     dtrti2(const char&,const char&,const long&,double*,const long&,long&);
RWLAPKDECL void     dtrtri(const char&,const char&,const long&,double*,const long&,long&);
RWLAPKDECL void     dtrtrs(const char&,const char&,const char&,const long&,const long&,double*,const long&,double*,const long&,long&);
RWLAPKDECL void     dtzrqf(const long&,const long&,double*,const long&,double[],long&);
RWLAPKDECL double   dzsum1(const long&,DComplex[],const long&);

RWLAPKDECL void zbdsqr(const char&,const long&,const long&,const long&,const long&,double[],double[],DComplex*,const long&,DComplex*,const long&,DComplex*,const long&,double[],long&);
RWLAPKDECL void zdrscl(const long&,const double&,DComplex[],const long&);
RWLAPKDECL void zgbcon(const char&,const long&,const long&,const long&,DComplex*,const long&,long[],const double&,double&,DComplex[],double[],long&);
RWLAPKDECL void zgbequ(const long&,const long&,const long&,const long&,DComplex*,const long&,double[],double[],double&,double&,double&,long&);
RWLAPKDECL void zgbrfs(const char&,const long&,const long&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,long[],DComplex*,const long&,DComplex*,const long&,double[],double[],DComplex[],double[],long&);
RWLAPKDECL void zgbsv(const long&,const long&,const long&,const long&,DComplex*,const long&,long[],DComplex*,const long&,long&);
RWLAPKDECL void zgbsvx(const char&,const char&,const long&,const long&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,long[],char&,double[],double[],DComplex*,const long&,DComplex*,const long&,double&,double[],double[],DComplex[],double[],long&);
RWLAPKDECL void zgbtf2(const long&,const long&,const long&,const long&,DComplex*,const long&,long[],long&);
RWLAPKDECL void zgbtrf(const long&,const long&,const long&,const long&,DComplex*,const long&,long[],long&);
RWLAPKDECL void zgbtrs(const char&,const long&,const long&,const long&,const long&,DComplex*,const long&,long[],DComplex*,const long&,long&);
RWLAPKDECL void zgebak(const char&,const char&,const long&,const long&,const long&,double[],const long&,DComplex*,const long&,long&);
RWLAPKDECL void zgebal(const char&,const long&,DComplex*,const long&,long&,long&,double[],long&);
RWLAPKDECL void zgebd2(const long&,const long&,DComplex*,const long&,double[],double[],DComplex[],DComplex[],DComplex[],long&);
RWLAPKDECL void zgebrd(const long&,const long&,DComplex*,const long&,double[],double[],DComplex[],DComplex[],DComplex[],const long&,long&);
RWLAPKDECL void rwlapkfuncexport zgecon(const char&,const long&,DComplex*,const long&,const double&,double&,DComplex[],double[],long&);
RWLAPKDECL void zgeequ(const long&,const long&,DComplex*,const long&,double[],double[],double&,double&,double&,long&);
RWLAPKDECL void zgees(const char&,const char&,int(*select)(DComplex[]),const long&,DComplex*,const long&,const long&,DComplex[],DComplex*,const long&,DComplex[],const long&,double[],int[],long&);
RWLAPKDECL void zgeesx(const char&,const char&,int(*select)(DComplex[]),const char&,const long&,DComplex*,const long&,const long&,DComplex[],DComplex*,const long&,const double&,const double&,DComplex[],const long&,double[],int[],long&);
RWLAPKDECL void zgeev(const char&,const char&,const long&,DComplex*,const long&,DComplex[],DComplex*,const long&,DComplex*,const long&,DComplex[],const long&,double[],long&);
RWLAPKDECL void zgeevx(const char&,const char&,const char&,const char&,const long&,DComplex*,const long&,DComplex[],DComplex*,const long&,DComplex*,const long&,long&,long&,double[],double&,double[],double[],DComplex[],const long&,double[],long&);
RWLAPKDECL void zgehd2(const long&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex[],long&);
RWLAPKDECL void zgehrd(const long&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex[],const long&,long&);
RWLAPKDECL void zgelq2(const long&,const long&,DComplex*,const long&,DComplex[],DComplex[],long&);
RWLAPKDECL void zgelqf(const long&,const long&,DComplex*,const long&,DComplex[],DComplex[],const long&,long&);
RWLAPKDECL void zgels(const char&,const long&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,DComplex[],const long&,long&);
RWLAPKDECL void zgelss(const long&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,double[],const double&,long&,DComplex[],const long&,double[],long&);
RWLAPKDECL void zgelsx(const long&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,long[],const double&,const long&,DComplex[],double[],long&);
RWLAPKDECL void zgeql2(const long&,const long&,DComplex*,const long&,DComplex[],DComplex[],long&);
RWLAPKDECL void zgeqlf(const long&,const long&,DComplex*,const long&,DComplex[],DComplex[],const long&,long&);
RWLAPKDECL void zgeqpf(const long&,const long&,DComplex*,const long&,long[],DComplex[],DComplex[],double[],long&);
RWLAPKDECL void zgeqr2(const long&,const long&,DComplex*,const long&,DComplex[],DComplex[],long&);
RWLAPKDECL void zgeqrf(const long&,const long&,DComplex*,const long&,DComplex[],DComplex[],const long&,long&);
RWLAPKDECL void zgerfs(const char&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,long[],DComplex*,const long&,DComplex*,const long&,double[],double[],DComplex[],double[],long&);
RWLAPKDECL void zgerq2(const long&,const long&,DComplex*,const long&,DComplex[],DComplex[],long&);
RWLAPKDECL void zgerqf(const long&,const long&,DComplex*,const long&,DComplex[],DComplex[],const long&,long&);
RWLAPKDECL void zgesv(const long&,const long&,DComplex*,const long&,long[],DComplex*,const long&,long&);
RWLAPKDECL void zgesvd(const char&,const char&,const long&,const long&,DComplex*,const long&,double[],DComplex*,const long&,DComplex*,const long&,DComplex[],const long&,double[],long&);
RWLAPKDECL void zgesvx(const char&,const char&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,long[],char&,double[],double[],DComplex*,const long&,DComplex*,const long&,double&,double[],double[],DComplex[],double[],long&);
RWLAPKDECL void zgetf2(const long&,const long&,DComplex*,const long&,long[],long&);
RWLAPKDECL void rwlapkfuncexport zgetrf(const long&,const long&,DComplex*,const long&,long[],long&);
RWLAPKDECL void rwlapkfuncexport zgetri(const long&,DComplex*,const long&,long[],DComplex[],const long&,long&);
RWLAPKDECL void rwlapkfuncexport zgetrs(const char&,const long&,const long&,DComplex*,const long&,long[],DComplex*,const long&,long&);
RWLAPKDECL void zgtcon(const char&,const long&,DComplex[],DComplex[],DComplex[],DComplex[],long[],const double&,double&,DComplex[],long&);
RWLAPKDECL void zgtrfs(const char&,const long&,const long&,DComplex[],DComplex[],DComplex[],DComplex[],DComplex[],DComplex[],DComplex[],long[],DComplex*,const long&,DComplex*,const long&,double[],double[],DComplex[],double[],long&);
RWLAPKDECL void zgtsv(const long&,const long&,DComplex[],DComplex[],DComplex[],DComplex*,const long&,long&);
RWLAPKDECL void zgtsvx(const char&,const char&,const long&,const long&,DComplex[],DComplex[],DComplex[],DComplex[],DComplex[],DComplex[],DComplex[],long[],DComplex*,const long&,DComplex*,const long&,double&,double[],double[],DComplex[],double[],long&);
RWLAPKDECL void zgttrf(const long&,DComplex[],DComplex[],DComplex[],DComplex[],long[],long&);
RWLAPKDECL void zgttrs(const char&,const long&,const long&,DComplex[],DComplex[],DComplex[],DComplex[],long[],DComplex*,const long&,long&);
RWLAPKDECL void zhbev(const char&,const char&,const long&,const long&,DComplex*,const long&,double[],DComplex*,const long&,DComplex[],double[],long&);
RWLAPKDECL void zhbevx(const char&,const char&,const char&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,const double&,const double&,const long&,const long&,const double&,long&,double[],DComplex*,const long&,DComplex[],double[],long[],long[],long&);
RWLAPKDECL void zhbtrd(const char&,const char&,const long&,const long&,DComplex*,const long&,double[],double[],DComplex*,const long&,DComplex[],long&);
RWLAPKDECL void zhecon(const char&,const long&,DComplex*,const long&,long[],const double&,double&,DComplex[],long&);
RWLAPKDECL void zheev(const char&,const char&,const long&,DComplex*,const long&,double[],DComplex[],const long&,double[],long&);
RWLAPKDECL void zheevx(const char&,const char&,const char&,const long&,DComplex*,const long&,const double&,const double&,const long&,const long&,const double&,long&,double[],DComplex*,const long&,DComplex[],const long&,double[],long[],long[],long&);
RWLAPKDECL void zhegs2(const long&,const char&,const long&,DComplex*,const long&,DComplex*,const long&,long&);
RWLAPKDECL void zhegst(const long&,const char&,const long&,DComplex*,const long&,DComplex*,const long&,long&);
RWLAPKDECL void zhegv(const long&,const char&,const char&,const long&,DComplex*,const long&,DComplex*,const long&,double[],DComplex[],const long&,double[],long&);
RWLAPKDECL void zherfs(const char&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,long[],DComplex*,const long&,DComplex*,const long&,double[],double[],DComplex[],double[],long&);
RWLAPKDECL void zhesv(const char&,const long&,const long&,DComplex*,const long&,long[],DComplex*,const long&,DComplex[],const long&,long&);
RWLAPKDECL void zhesvx(const char&,const char&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,long[],DComplex*,const long&,DComplex*,const long&,double&,double[],double[],DComplex[],const long&,double[],long&);
RWLAPKDECL void zhetd2(const char&,const long&,DComplex*,const long&,double[],double[],DComplex[],long&);
RWLAPKDECL void zhetf2(const char&,const long&,DComplex*,const long&,long[],long&);
RWLAPKDECL void zhetrd(const char&,const long&,DComplex*,const long&,double[],double[],DComplex[],DComplex[],const long&,long&);
RWLAPKDECL void zhetrf(const char&,const long&,DComplex*,const long&,long[],DComplex[],const long&,long&);
RWLAPKDECL void zhetri(const char&,const long&,DComplex*,const long&,long[],DComplex[],long&);
RWLAPKDECL void zhetrs(const char&,const long&,const long&,DComplex*,const long&,long[],DComplex*,const long&,long&);
RWLAPKDECL void zhpcon(const char&,const long&,DComplex[],long[],const double&,double&,DComplex[],long&);
RWLAPKDECL void zhpev(const char&,const char&,const long&,DComplex[],double[],DComplex*,const long&,DComplex[],double[],long&);
RWLAPKDECL void zhpevx(const char&,const char&,const char&,const long&,DComplex[],const double&,const double&,const long&,const long&,const double&,long&,double[],DComplex*,const long&,DComplex[],double[],long[],long[],long&);
RWLAPKDECL void zhpgst(const long&,const char&,const long&,DComplex[],DComplex[],long&);
RWLAPKDECL void zhpgv(const long&,const char&,const char&,const long&,DComplex[],DComplex[],double[],DComplex*,const long&,DComplex[],double[],long&);
RWLAPKDECL void zhprfs(const char&,const long&,const long&,DComplex[],DComplex[],long[],DComplex*,const long&,DComplex*,const long&,double[],double[],DComplex[],double[],long&);
RWLAPKDECL void zhpsv(const char&,const long&,const long&,DComplex[],long[],DComplex*,const long&,long&);
RWLAPKDECL void zhpsvx(const char&,const char&,const long&,const long&,DComplex[],DComplex[],long[],DComplex*,const long&,DComplex*,const long&,double&,double[],double[],DComplex[],double[],long&);
RWLAPKDECL void zhptrd(const char&,const long&,DComplex[],double[],double[],DComplex[],long&);
RWLAPKDECL void zhptrf(const char&,const long&,DComplex[],long[],long&);
RWLAPKDECL void zhptri(const char&,const long&,DComplex[],long[],DComplex[],long&);
RWLAPKDECL void zhptrs(const char&,const long&,const long&,DComplex[],long[],DComplex*,const long&,long&);
RWLAPKDECL void zhsein(const char&,const char&,const char&,int[],const long&,DComplex*,const long&,DComplex[],DComplex*,const long&,DComplex*,const long&,const long&,long&,DComplex[],double[],long[],long[],long&);
RWLAPKDECL void zhseqr(const char&,const char&,const long&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex*,const long&,DComplex[],const long&,long&);
RWLAPKDECL void zlabrd(const long&,const long&,const long&,DComplex*,const long&,double[],double[],DComplex[],DComplex[],DComplex*,const long&,DComplex*,const long&);
RWLAPKDECL void zlacgv(const long&,DComplex[],const long&);
RWLAPKDECL void zlacon(const long&,DComplex[],DComplex[],double&,long&);
RWLAPKDECL void zlacpy(const char&,const long&,const long&,DComplex*,const long&,DComplex*,const long&);
RWLAPKDECL void zlacrt(const long&,DComplex[],const long&,DComplex[],const long&,const DComplex&,const DComplex&);
RWLAPKDECL DComplex zladiv(const DComplex&,const DComplex&);
RWLAPKDECL void zlaein(const int&,const int&,const long&,DComplex*,const long&,const DComplex&,DComplex[],DComplex*,const long&,double[],const double&,const double&,long&);
RWLAPKDECL void zlaesy(const DComplex&,const DComplex&,const DComplex&,DComplex&,DComplex&,DComplex&,DComplex&,DComplex&);
RWLAPKDECL void zlaev2(const DComplex&,const DComplex&,const DComplex&,double&,double&,double&,DComplex&);
RWLAPKDECL void zlagtm(const char&,const long&,const long&,const double&,DComplex[],DComplex[],DComplex[],DComplex*,const long&,const double&,DComplex*,const long&);
RWLAPKDECL void zlahef(const char&,const long&,const long&,long&,DComplex*,const long&,long[],DComplex*,const long&,long&);
RWLAPKDECL void zlahqr(const int&,const int&,const long&,const long&,const long&,DComplex*,const long&,DComplex[],const long&,const long&,DComplex*,const long&,long&);
RWLAPKDECL void zlahrd(const long&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex*,const long&,DComplex*,const long&);
RWLAPKDECL void zlaic1(const long&,const long&,DComplex[],const double&,DComplex[],const DComplex&,double&,DComplex&,DComplex&);
RWLAPKDECL double zlangb(const char&,const long&,const long&,const long&,DComplex*,const long&,double[]);
RWLAPKDECL double rwlapkfuncexport zlange(const char&,const long&,const long&,DComplex*,const long&,double[]);
RWLAPKDECL double zlangt(const char&,const long&,DComplex[],DComplex[],DComplex[]);
RWLAPKDECL double zlanhb(const char&,const char&,const long&,const long&,DComplex*,const long&,double[]);
RWLAPKDECL double zlanhe(const char&,const char&,const long&,DComplex*,const long&,double[]);
RWLAPKDECL double zlanhp(const char&,const char&,const long&,DComplex[],double[]);
RWLAPKDECL double zlanhs(const char&,const long&,DComplex*,const long&,double[]);
RWLAPKDECL double zlansb(const char&,const char&,const long&,const long&,DComplex*,const long&,double[]);
RWLAPKDECL double zlansp(const char&,const char&,const long&,DComplex[],double[]);
RWLAPKDECL double zlanst(const char&,const long&,double[],DComplex[]);
RWLAPKDECL double zlansy(const char&,const char&,const long&,DComplex*,const long&,double[]);
RWLAPKDECL double zlantb(const char&,const char&,const char&,const long&,const long&,DComplex*,const long&,double[]);
RWLAPKDECL double zlantp(const char&,const char&,const char&,const long&,DComplex[],double[]);
RWLAPKDECL double zlantr(const char&,const char&,const char&,const long&,const long&,DComplex*,const long&,double[]);
RWLAPKDECL void zlaqgb(const long&,const long&,const long&,const long&,DComplex*,const long&,double[],double[],double&,double&,const double&,char&);
RWLAPKDECL void zlaqge(const long&,const long&,DComplex*,const long&,double[],double[],const double&,const double&,const double&,char&);
RWLAPKDECL void zlaqsb(const char&,const long&,const long&,DComplex*,const long&,double[],const double&,const double&,char&);
RWLAPKDECL void zlaqsp(const char&,const long&,DComplex[],double[],const double&,const double&,char&);
RWLAPKDECL void zlaqsy(const char&,const long&,DComplex*,const long&,double[],const double&,const double&,char&);
RWLAPKDECL void zlar2v(const long&,DComplex[],DComplex[],DComplex[],const long&,double[],DComplex[],const long&);
RWLAPKDECL void zlarf(const char&,const long&,const long&,DComplex[],const long&,const DComplex&,DComplex*,const long&,DComplex[]);
RWLAPKDECL void zlarfb(const char&,const char&,const char&,const char&,const long&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,DComplex*,const long&,DComplex*,const long&);
RWLAPKDECL void zlarfg(const long&,DComplex&,DComplex[],const long&,DComplex&);
RWLAPKDECL void zlarft(const char&,const char&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex*,const long&);
RWLAPKDECL void zlarfx(const char&,const long&,const long&,DComplex[],const DComplex&,DComplex*,const long&,DComplex[]);
RWLAPKDECL void zlargv(const long&,DComplex[],const long&,DComplex[],const long&,double[],const long&);
RWLAPKDECL void zlarnv(const long&,long[],const long&,DComplex[]);
RWLAPKDECL void zlartg(const DComplex&,const DComplex&,double&,DComplex&,DComplex&);
RWLAPKDECL void zlartv(const long&,DComplex[],const long&,DComplex[],const long&,double[],DComplex[],const long&);
RWLAPKDECL void zlascl(const char&,const long&,const long&,const double&,const double&,const long&,const long&,DComplex*,const long&,long&);
RWLAPKDECL void zlaset(const char&,const long&,const long&,const DComplex&,const DComplex&,DComplex*,const long&);
RWLAPKDECL void zlasr(const char&,const char&,const char&,const long&,const long&,double[],double[],DComplex*,const long&);
RWLAPKDECL void zlassq(const long&,DComplex[],const long&,double&,double&);
RWLAPKDECL void zlaswp(const long&,DComplex*,const long&,const long&,const long&,long[],const long&);
RWLAPKDECL void zlasyf(const char&,const long&,const long&,long&,DComplex*,const long&,long[],DComplex*,const long&,long&);
RWLAPKDECL void zlatbs(const char&,const char&,const char&,const char&,const long&,const long&,DComplex*,const long&,DComplex[],double&,double[],long&);
RWLAPKDECL void zlatps(const char&,const char&,const char&,const char&,const long&,DComplex[],DComplex[],double&,double[],long&);
RWLAPKDECL void zlatrd(const char&,const long&,const long&,DComplex*,const long&,double[],DComplex[],DComplex*,const long&);
RWLAPKDECL void zlatrs(const char&,const char&,const char&,const char&,const long&,DComplex*,const long&,DComplex[],double&,double[],long&);
RWLAPKDECL void zlatzm(const char&,const long&,const long&,DComplex[],const long&,const DComplex&,DComplex*,DComplex*,const long&,DComplex[]);
RWLAPKDECL void zlauu2(const char&,const long&,DComplex*,const long&,long&);
RWLAPKDECL void zlauum(const char&,const long&,DComplex*,const long&,long&);
RWLAPKDECL void zlazro(const long&,const long&,const DComplex&,const DComplex&,DComplex*,const long&);
RWLAPKDECL void zpbcon(const char&,const long&,const long&,DComplex*,const long&,const double&,double&,DComplex[],double[],long&);
RWLAPKDECL void zpbequ(const char&,const long&,const long&,DComplex*,const long&,double[],double&,double&,long&);
RWLAPKDECL void zpbrfs(const char&,const long&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,DComplex*,const long&,DComplex*,const long&,double[],double[],DComplex[],double[],long&);
RWLAPKDECL void zpbsv(const char&,const long&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,long&);
RWLAPKDECL void zpbsvx(const char&,const char&,const long&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,char&,double[],DComplex*,const long&,DComplex*,const long&,double&,double[],double[],DComplex[],double[],long&);
RWLAPKDECL void zpbtf2(const char&,const long&,const long&,DComplex*,const long&,long&);
RWLAPKDECL void zpbtrf(const char&,const long&,const long&,DComplex*,const long&,long&);
RWLAPKDECL void zpbtrs(const char&,const long&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,long&);
RWLAPKDECL void zpocon(const char&,const long&,DComplex*,const long&,const double&,double&,DComplex[],double[],long&);
RWLAPKDECL void zpoequ(const long&,DComplex*,const long&,double[],double&,double&,long&);
RWLAPKDECL void zporfs(const char&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,DComplex*,const long&,DComplex*,const long&,double[],double[],DComplex[],double[],long&);
RWLAPKDECL void zposv(const char&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,long&);
RWLAPKDECL void zposvx(const char&,const char&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,char&,double[],DComplex*,const long&,DComplex*,const long&,double&,double[],double[],DComplex[],double[],long&);
RWLAPKDECL void zpotf2(const char&,const long&,DComplex*,const long&,long&);
RWLAPKDECL void zpotrf(const char&,const long&,DComplex*,const long&,long&);
RWLAPKDECL void zpotri(const char&,const long&,DComplex*,const long&,long&);
RWLAPKDECL void zpotrs(const char&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,long&);
RWLAPKDECL void zppcon(const char&,const long&,DComplex[],const double&,double&,DComplex[],double[],long&);
RWLAPKDECL void zppequ(const char&,const long&,DComplex[],double[],double&,double&,long&);
RWLAPKDECL void zpprfs(const char&,const long&,const long&,DComplex[],DComplex[],DComplex*,const long&,DComplex*,const long&,double[],double[],DComplex[],double[],long&);
RWLAPKDECL void zppsv(const char&,const long&,const long&,DComplex[],DComplex*,const long&,long&);
RWLAPKDECL void zppsvx(const char&,const char&,const long&,const long&,DComplex[],DComplex[],char&,double[],DComplex*,const long&,DComplex*,const long&,double&,double[],double[],DComplex[],double[],long&);
RWLAPKDECL void zpptrf(const char&,const long&,DComplex[],long&);
RWLAPKDECL void zpptri(const char&,const long&,DComplex[],long&);
RWLAPKDECL void zpptrs(const char&,const long&,const long&,DComplex[],DComplex*,const long&,long&);
RWLAPKDECL void zptcon(const long&,double[],DComplex[],const double&,double&,double[],long&);
RWLAPKDECL void zpteqr(const char&,const long&,double[],double[],DComplex*,const long&,double[],long&);
RWLAPKDECL void zptrfs(const char&,const long&,const long&,double[],DComplex[],double[],DComplex[],DComplex*,const long&,DComplex*,const long&,double[],double[],DComplex[],double[],long&);
RWLAPKDECL void zptsv(const long&,const long&,double[],DComplex[],DComplex*,const long&,long&);
RWLAPKDECL void zptsvx(const char&,const long&,const long&,double[],DComplex[],double[],DComplex[],DComplex*,const long&,DComplex*,const long&,double&,double[],double[],DComplex[],double[],long&);
RWLAPKDECL void zpttrf(const long&,double[],DComplex[],long&);
RWLAPKDECL void zpttrs(const char&,const long&,const long&,double[],DComplex[],DComplex*,const long&,long&);
RWLAPKDECL void zrot(const long&,DComplex[],const long&,DComplex[],const long&,const double&,const DComplex&);
RWLAPKDECL void zspcon(const char&,const long&,DComplex[],long[],const double&,double&,DComplex[],long&);
RWLAPKDECL void zspmv(const char&,const long&,const DComplex&,DComplex[],DComplex[],const long&,const DComplex&,DComplex[],const long&);
RWLAPKDECL void zspr(const char&,const long&,const DComplex&,DComplex[],const long&,DComplex[]);
RWLAPKDECL void zsprfs(const char&,const long&,const long&,DComplex[],DComplex[],long[],DComplex*,const long&,DComplex*,const long&,double[],double[],DComplex[],double[],long&);
RWLAPKDECL void zspsv(const char&,const long&,const long&,DComplex[],long[],DComplex*,const long&,long&);
RWLAPKDECL void zspsvx(const char&,const char&,const long&,const long&,DComplex[],DComplex[],long[],DComplex*,const long&,DComplex*,const long&,double&,double[],double[],DComplex[],double[],long&);
RWLAPKDECL void zsptrf(const char&,const long&,DComplex[],long[],long&);
RWLAPKDECL void zsptri(const char&,const long&,DComplex[],long[],DComplex[],long&);
RWLAPKDECL void zsptrs(const char&,const long&,const long&,DComplex[],long[],DComplex*,const long&,long&);
RWLAPKDECL void zstein(const long&,double[],double[],const long&,double[],long[],long[],DComplex*,const long&,double[],long[],long[],long&);
RWLAPKDECL void zsteqr(const char&,const long&,double[],double[],DComplex*,const long&,double[],long&);
RWLAPKDECL void zsycon(const char&,const long&,DComplex*,const long&,long[],const double&,double&,DComplex[],long&);
RWLAPKDECL void zsymv(const char&,const long&,const DComplex&,DComplex*,const long&,DComplex[],const long&,const DComplex&,DComplex[],const long&);
RWLAPKDECL void zsyr(const char&,const long&,const DComplex&,DComplex[],const long&,DComplex*,const long&);
RWLAPKDECL void zsyrfs(const char&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,long[],DComplex*,const long&,DComplex*,const long&,double[],double[],DComplex[],double[],long&);
RWLAPKDECL void zsysv(const char&,const long&,const long&,DComplex*,const long&,long[],DComplex*,const long&,DComplex[],const long&,long&);
RWLAPKDECL void zsysvx(const char&,const char&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,long[],DComplex*,const long&,DComplex*,const long&,double&,double[],double[],DComplex[],const long&,double[],long&);
RWLAPKDECL void zsytf2(const char&,const long&,DComplex*,const long&,long[],long&);
RWLAPKDECL void zsytrf(const char&,const long&,DComplex*,const long&,long[],DComplex[],const long&,long&);
RWLAPKDECL void zsytri(const char&,const long&,DComplex*,const long&,long[],DComplex[],long&);
RWLAPKDECL void zsytrs(const char&,const long&,const long&,DComplex*,const long&,long[],DComplex*,const long&,long&);
RWLAPKDECL void ztbcon(const char&,const char&,const char&,const long&,const long&,DComplex*,const long&,double&,DComplex[],double[],long&);
RWLAPKDECL void ztbrfs(const char&,const char&,const char&,const long&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,DComplex*,const long&,double[],double[],DComplex[],double[],long&);
RWLAPKDECL void ztbtrs(const char&,const char&,const char&,const long&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,long&);
RWLAPKDECL void ztpcon(const char&,const char&,const char&,const long&,DComplex[],double&,DComplex[],double[],long&);
RWLAPKDECL void ztprfs(const char&,const char&,const char&,const long&,const long&,DComplex[],DComplex*,const long&,DComplex*,const long&,double[],double[],DComplex[],double[],long&);
RWLAPKDECL void ztptri(const char&,const char&,const long&,DComplex[],long&);
RWLAPKDECL void ztptrs(const char&,const char&,const char&,const long&,const long&,DComplex[],DComplex*,const long&,long&);
RWLAPKDECL void ztrcon(const char&,const char&,const char&,const long&,DComplex*,const long&,double&,DComplex[],double[],long&);
RWLAPKDECL void ztrevc(const char&,const char&,int[],const long&,DComplex*,const long&,DComplex*,const long&,DComplex*,const long&,const long&,long&,DComplex[],double[],long&);
RWLAPKDECL void ztrexc(const char&,const long&,DComplex*,const long&,DComplex*,const long&,const long&,const long&,long&);
RWLAPKDECL void ztrrfs(const char&,const char&,const char&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,DComplex*,const long&,double[],double[],DComplex[],double[],long&);
RWLAPKDECL void ztrsen(const char&,const char&,int[],const long&,DComplex*,const long&,DComplex*,const long&,DComplex[],long&,double&,double&,DComplex[],const long&,long&);
RWLAPKDECL void ztrsna(const char&,const char&,int[],const long&,DComplex*,const long&,DComplex*,const long&,DComplex*,const long&,double[],double[],const long&,long&,DComplex*,const long&,double[],long&);
RWLAPKDECL void ztrsyl(const char&,const char&,const long&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,DComplex*,const long&,double&,long&);
RWLAPKDECL void ztrti2(const char&,const char&,const long&,DComplex*,const long&,long&);
RWLAPKDECL void ztrtri(const char&,const char&,const long&,DComplex*,const long&,long&);
RWLAPKDECL void ztrtrs(const char&,const char&,const char&,const long&,const long&,DComplex*,const long&,DComplex*,const long&,long&);
RWLAPKDECL void ztzrqf(const long&,const long&,DComplex*,const long&,DComplex[],long&);
RWLAPKDECL void zung2l(const long&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex[],long&);
RWLAPKDECL void zung2r(const long&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex[],long&);
RWLAPKDECL void zungbr(const char&,const long&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex[],const long&,long&);
RWLAPKDECL void zunghr(const long&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex[],const long&,long&);
RWLAPKDECL void zungl2(const long&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex[],long&);
RWLAPKDECL void zunglq(const long&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex[],const long&,long&);
RWLAPKDECL void zungql(const long&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex[],const long&,long&);
RWLAPKDECL void zungqr(const long&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex[],const long&,long&);
RWLAPKDECL void zungr2(const long&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex[],long&);
RWLAPKDECL void zungrq(const long&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex[],const long&,long&);
RWLAPKDECL void zungtr(const char&,const long&,DComplex*,const long&,DComplex[],DComplex[],const long&,long&);
RWLAPKDECL void zunm2l(const char&,const char&,const long&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex*,const long&,DComplex[],long&);
RWLAPKDECL void zunm2r(const char&,const char&,const long&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex*,const long&,DComplex[],long&);
RWLAPKDECL void zunmbr(const char&,const char&,const char&,const long&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex*,const long&,DComplex[],const long&,long&);
RWLAPKDECL void zunmhr(const char&,const char&,const long&,const long&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex*,const long&,DComplex[],const long&,long&);
RWLAPKDECL void zunml2(const char&,const char&,const long&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex*,const long&,DComplex[],long&);
RWLAPKDECL void zunmlq(const char&,const char&,const long&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex*,const long&,DComplex[],const long&,long&);
RWLAPKDECL void zunmql(const char&,const char&,const long&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex*,const long&,DComplex[],const long&,long&);
RWLAPKDECL void zunmqr(const char&,const char&,const long&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex*,const long&,DComplex[],const long&,long&);
RWLAPKDECL void zunmr2(const char&,const char&,const long&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex*,const long&,DComplex[],long&);
RWLAPKDECL void zunmrq(const char&,const char&,const long&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex*,const long&,DComplex[],const long&,long&);
RWLAPKDECL void zunmtr(const char&,const char&,const char&,const long&,const long&,DComplex*,const long&,DComplex[],DComplex*,const long&,DComplex[],const long&,long&);
RWLAPKDECL void zupgtr(const char&,const long&,DComplex[],DComplex[],DComplex*,const long&,DComplex[],long&);
RWLAPKDECL void zupmtr(const char&,const char&,const char&,const long&,const long&,DComplex[],DComplex[],DComplex*,const long&,DComplex[],long&);

RWLAPKDECL void     sbdsqr(const char&,const long&,const long&,const long&,const long&,float[],float[],float*,const long&,float*,const long&,float*,const long&,float[],long&);
RWLAPKDECL void     sgbcon(const char&,long&,long&,long&,float*,long&,long[],float&,float&,float[],long[],long&);
RWLAPKDECL void     sgbequ(const long&,const long&,const long&,const long&,float*,const long&,float[],float[],float&,float&,float&,long&);
RWLAPKDECL void     sgbrfs(const char&,const long&,const long&,const long&,const long&,float*,const long&,float*,const long&,long[],float*,const long&,float*,const long&,float[],float[],float[],long[],long&);
RWLAPKDECL void     sgbsv(const long&,const long&,const long&,const long&,float*,const long&,long[],float*,const long&,long&);
RWLAPKDECL void     sgbsvx(const char&,const char&,long&,long&,long&,long&,float*,long&,float*,long&,long[],char&,float[],float[],float*,long&,float*,long&,float&,float[],float[],float[],long[],long&);
RWLAPKDECL void     sgbtf2(const long&,const long&,const long&,const long&,float*,const long&,long[],long&);
RWLAPKDECL void     sgbtrf(const long&,const long&,const long&,const long&,float*,const long&,long[],long&);
RWLAPKDECL void     sgbtrs(const char&,const long&,const long&,const long&,const long&,float*,const long&,long[],float*,const long&,long&);
RWLAPKDECL void     sgebak(const char&,const char&,const long&,const long&,const long&,float[],const long&,float*,const long&,long&);
RWLAPKDECL void     sgebal(const char&,const long&,float*,const long&,long&,long&,float[],long&);
RWLAPKDECL void     sgebd2(const long&,const long&,float*,const long&,float[],float[],float[],float[],float[],long&);
RWLAPKDECL void     sgebrd(const long&,const long&,float*,const long&,float[],float[],float[],float[],float[],const long&,long&);
RWLAPKDECL void rwlapkfuncexport     sgecon(const char&,long&,float*,long&,float&,float&,float[],long[],long&);
RWLAPKDECL void     sgeequ(const long&,const long&,float*,const long&,float[],float[],float&,float&,float&,long&);
RWLAPKDECL void     sgees(const char&,const char&,int(*select)(float[],float[]),const long&,float*,const long&,const long&,float[],float[],float*,const long&,float[],const long&,int[],long&);
RWLAPKDECL void     sgeesx(const char&,const char&,int(*select)(float[],float[]),const char&,const long&,float*,const long&,const long&,float[],float[],float*,const long&,const float&,const float&,float[],const long&,long[],const long&,int[],long&);
RWLAPKDECL void     sgeev(const char&,const char&,const long&,float*,const long&,float[],float[],float*,const long&,float*,const long&,float[],const long&,long&);
RWLAPKDECL void     sgeevx(const char&,const char&,const char&,const char&,long&,float*,long&,float[],float[],float*,long&,float*,long&,long&,long&,float[],float&,float[],float[],float[],long&,long[],long&);
RWLAPKDECL void     sgehd2(const long&,const long&,const long&,float*,const long&,float[],float[],long&);
RWLAPKDECL void     sgehrd(const long&,const long&,const long&,float*,const long&,float[],float[],const long&,long&);
RWLAPKDECL void     sgelq2(const long&,const long&,float*,const long&,float[],float[],long&);
RWLAPKDECL void     sgelqf(const long&,const long&,float*,const long&,float[],float[],const long&,long&);
RWLAPKDECL void     sgels(const char&,const long&,const long&,const long&,float*,const long&,float*,const long&,float[],const long&,long&);
RWLAPKDECL void     sgelss(const long&,const long&,const long&,float*,const long&,float*,const long&,float[],float&,long&,float[],long&,long&);
RWLAPKDECL void     sgelsx(const long&,const long&,const long&,float*,const long&,float*,const long&,long[],const float&,long&,float[],long&);
RWLAPKDECL void     sgeql2(const long&,const long&,float*,const long&,float[],float[],long&);
RWLAPKDECL void     sgeqlf(const long&,const long&,float*,const long&,float[],float[],const long&,long&);
RWLAPKDECL void     sgeqpf(const long&,const long&,float*,const long&,long[],float[],float[],long&);
RWLAPKDECL void     sgeqr2(const long&,const long&,float*,const long&,float[],float[],long&);
RWLAPKDECL void     sgeqrf(const long&,const long&,float*,const long&,float[],float[],const long&,long&);
RWLAPKDECL void     sgerfs(const char&,const long&,const long&,float*,const long&,float*,const long&,long[],float*,const long&,float*,const long&,float[],float[],float[],long[],long&);
RWLAPKDECL void     sgerq2(const long&,const long&,float*,const long&,float[],float[],long&);
RWLAPKDECL void     sgerqf(const long&,const long&,float*,const long&,float[],float[],const long&,long&);
RWLAPKDECL void     sgesv(const long&,const long&,float*,const long&,long[],float*,const long&,long&);
RWLAPKDECL void     sgesvd(const char&,const char&,const long&,const long&,float*,const long&,float[],float*,const long&,float*,const long&,float[],const long&,long&);
RWLAPKDECL void     sgesvx(const char&,const char&,long&,long&,float*,long&,float*,long&,long[],char&,float[],float[],float*,long&,float*,long&,float&,float[],float[],float[],long[],long&);
RWLAPKDECL void     sgetf2(const long&,const long&,float*,const long&,long[],long&);
RWLAPKDECL void rwlapkfuncexport     sgetrf(const long&,const long&,float*,const long&,long[],long&);
RWLAPKDECL void rwlapkfuncexport     sgetri(const long&,float*,const long&,long[],float[],const long&,long&);
RWLAPKDECL void rwlapkfuncexport     sgetrs(const char&,const long&,const long&,float*,const long&,long[],float*,const long&,long&);
RWLAPKDECL void     sgtcon(const char&,long&,float[],float[],float[],float[],long[],float&,float&,float[],long[],long&);
RWLAPKDECL void     sgtrfs(const char&,const long&,const long&,float[],float[],float[],float[],float[],float[],float[],long[],float*,const long&,float*,const long&,float[],float[],float[],long[],long&);
RWLAPKDECL void     sgtsv(const long&,const long&,float[],float[],float[],float*,const long&,long&);
RWLAPKDECL void     sgtsvx(const char&,const char&,long&,long&,float[],float[],float[],float[],float[],float[],float[],long[],float*,long&,float*,long&,float&,float[],float[],float[],long[],long&);
RWLAPKDECL void     sgttrf(const long&,float[],float[],float[],float[],long[],long&);
RWLAPKDECL void     sgttrs(const char&,const long&,const long&,float[],float[],float[],float[],long[],float*,const long&,long&);
RWLAPKDECL void     shsein(const char&,const char&,const char&,int[],long&,float*,long&,float[],float[],float*,long&,float*,long&,long&,long&,float[],long[],long[],long&);
RWLAPKDECL void     shseqr(const char&,const char&,const long&,const long&,const long&,float*,const long&,float[],float[],float*,const long&,float[],const long&,long&);
RWLAPKDECL void     slabad(float&,float&);
RWLAPKDECL void     slabrd(const long&,const long&,const long&,float*,const long&,float[],float[],float[],float[],float*,const long&,float*,const long&);
RWLAPKDECL void     slacon(const long&,float[],float[],long[],float&,long&);
RWLAPKDECL void     slacpy(const char&,const long&,const long&,float*,const long&,float*,const long&);
RWLAPKDECL void     sladiv(const float&,const float&,const float&,const float&,float&,float&);
RWLAPKDECL void     slae2(const float&,const float&,const float&,float&,float&);
RWLAPKDECL void     slaebz(const long&,const long&,const long&,const long&,const long&,const long&,const float&,const float&,const float&,float[],float[],float[],long[],float*,float[],long&,long*,float[],long[],long&);
RWLAPKDECL void     slaein(const int&,const int&,const long&,float*,const long&,const float&,const float&,float[],float[],float*,const long&,float[],const float&,const float&,const float&,long&);
RWLAPKDECL void     slaev2(const float&,const float&,const float&,float&,float&,float&,float&);
RWLAPKDECL void     slaexc(const int&,const long&,float*,const long&,float*,const long&,const long&,const long&,const long&,float[],long&);
RWLAPKDECL void     slagtf(const long&,float[],const float&,float[],float[],const float&,float[],long[],long&);
RWLAPKDECL void     slagtm(const char&,const long&,const long&,const float&,float[],float[],float[],float*,const long&,const float&,float*,const long&);
RWLAPKDECL void     slagts(const long&,const long&,float[],float[],float[],float[],long[],float[],float&,long&);
RWLAPKDECL void     slahqr(const int&,const int&,const long&,const long&,const long&,float*,const long&,float[],float[],const long&,const long&,float*,const long&,long&);
RWLAPKDECL void     slahrd(const long&,const long&,const long&,float*,const long&,float[],float*,const long&,float*,const long&);
RWLAPKDECL void     slaic1(const long&,const long&,float[],const float&,float[],const float&,float&,float&,float&);
RWLAPKDECL void     slaln2(const int&,const long&,const long&,const float&,const float&,float*,const long&,const float&,const float&,float*,const long&,const float&,const float&,float*,const long&,float&,float&,long&);
RWLAPKDECL float    slamch(const char&);
RWLAPKDECL float    slangb(const char&,const long&,const long&,const long&,float*,const long&,float[]);
RWLAPKDECL float rwlapkfuncexport    slange(const char&,const long&,const long&,float*,const long&,float[]);
RWLAPKDECL float    slangt(const char&,const long&,float[],float[],float[]);
RWLAPKDECL float    slanhs(const char&,const long&,float*,const long&,float[]);
RWLAPKDECL float    slansb(const char&,const char&,const long&,const long&,float*,const long&,float[]);
RWLAPKDECL float    slansp(const char&,const char&,const long&,float[],float[]);
RWLAPKDECL float    slanst(const char&,const long&,float[],float[]);
RWLAPKDECL float    slansy(const char&,const char&,const long&,float*,const long&,float[]);
RWLAPKDECL float    slantb(const char&,const char&,const char&,const long&,const long&,float*,const long&,float[]);
RWLAPKDECL float    slantp(const char&,const char&,const char&,const long&,float[],float[]);
RWLAPKDECL float    slantr(const char&,const char&,const char&,const long&,const long&,float*,const long&,float[]);
RWLAPKDECL void     slanv2(float&,float&,float&,float&,float&,float&,float&,float&,float&,float&);
RWLAPKDECL float    slapy2(const float&,const float&);
RWLAPKDECL float    slapy3(const float&,const float&,const float&);
RWLAPKDECL void     slaqgb(const long&,const long&,const long&,const long&,float*,const long&,float[],float[],float&,float&,float&,char&);
RWLAPKDECL void     slaqge(const long&,const long&,float*,const long&,float[],float[],float&,float&,float&,char&);
RWLAPKDECL void     slaqsb(const char&,long&,long&,float*,long&,float[],float&,float&,char&);
RWLAPKDECL void     slaqsp(const char&,long&,float[],float[],float&,float&,char&);
RWLAPKDECL void     slaqsy(const char&,long&,float*,long&,float[],float&,float&,char&);
RWLAPKDECL void     slaqtr(const int&,const int&,const long&,float*,const long&,float[],const float&,float&,float[],float[],long&);
RWLAPKDECL void     slar2v(const long&,float[],float[],float[],const long&,float[],float[],const long&);
RWLAPKDECL void     slarf(const char&,const long&,const long&,float[],const long&,const float&,float*,const long&,float[]);
RWLAPKDECL void     slarfb(const char&,const char&,const char&,const char&,const long&,const long&,const long&,float*,const long&,float*,const long&,float*,const long&,float*,const long&);
RWLAPKDECL void     slarfg(const long&,float&,float[],const long&,float&);
RWLAPKDECL void     slarft(const char&,const char&,const long&,const long&,float*,const long&,float[],float*,const long&);
RWLAPKDECL void     slarfx(const char&,const long&,const long&,float[],const float&,float*,const long&,float[]);
RWLAPKDECL void     slargv(const long&,float[],const long&,float[],const long&,float[],const long&);
RWLAPKDECL void     slarnv(const long&,long[],const long&,float[]);
RWLAPKDECL void     slartg(const float&,const float&,float&,float&,float&);
RWLAPKDECL void     slartv(const long&,float[],const long&,float[],const long&,float[],float[],const long&);
RWLAPKDECL void     slaruv(long[],const long&,float[]);
RWLAPKDECL void     slas2(const float&,const float&,const float&,float&,float&);
RWLAPKDECL void     slascl(const char&,const long&,const long&,const float&,const float&,const long&,const long&,float*,const long&,long&);
RWLAPKDECL void     slaset(const char&,const long&,const long&,const float&,const float&,float*,const long&);
RWLAPKDECL void     slasr(const char&,const char&,const char&,const long&,const long&,float[],float[],float*,const long&);
RWLAPKDECL void     slassq(const long&,float[],const long&,float&,float&);
RWLAPKDECL void     slasv2(const float&,const float&,const float&,float&,float&,float&,float&,float&,float&);
RWLAPKDECL void     slaswp(const long&,float*,const long&,const long&,const long&,long[],const long&);
RWLAPKDECL void     slasy2(const int&,const int&,const long&,const long&,const long&,float*,const long&,float*,const long&,float*,const long&,float&,float*,const long&,float&,long&);
RWLAPKDECL void     slasyf(const char&,const long&,const long&,long&,float*,const long&,long[],float*,const long&,long&);
RWLAPKDECL void     slatbs(const char&,const char&,const char&,const char&,const long&,const long&,float*,const long&,float[],float&,float[],long&);
RWLAPKDECL void     slatps(const char&,const char&,const char&,const char&,long&,float[],float[],float&,float[],long&);
RWLAPKDECL void     slatrd(const char&,const long&,const long&,float*,const long&,float[],float[],float*,const long&);
RWLAPKDECL void     slatrs(const char&,const char&,const char&,const char&,const long&,float*,const long&,float[],float&,float[],long&);
RWLAPKDECL void     slatzm(const char&,const long&,const long&,float[],const long&,const float&,float*,float*,const long&,float[]);
RWLAPKDECL void     slauu2(const char&,const long&,float*,const long&,long&);
RWLAPKDECL void     slauum(const char&,const long&,float*,const long&,long&);
RWLAPKDECL void     slazro(const long&,const long&,const float&,const float&,float*,const long&);
RWLAPKDECL void     sopgtr(const char&,const long&,float[],float[],float*,const long&,float[],long&);
RWLAPKDECL void     sopmtr(const char&,const char&,const char&,const long&,const long&,float[],float[],float*,const long&,float[],long&);
RWLAPKDECL void     sorg2l(const long&,const long&,const long&,float*,const long&,float[],float[],long&);
RWLAPKDECL void     sorg2r(const long&,const long&,const long&,float*,const long&,float[],float[],long&);
RWLAPKDECL void     sorgbr(const char&,const long&,const long&,const long&,float*,const long&,float[],float[],const long&,long&);
RWLAPKDECL void     sorghr(const long&,const long&,const long&,float*,const long&,float[],float[],const long&,long&);
RWLAPKDECL void     sorgl2(const long&,const long&,const long&,float*,const long&,float[],float[],long&);
RWLAPKDECL void     sorglq(const long&,const long&,const long&,float*,const long&,float[],float[],const long&,long&);
RWLAPKDECL void     sorgql(const long&,const long&,const long&,float*,const long&,float[],float[],const long&,long&);
RWLAPKDECL void     sorgqr(const long&,const long&,const long&,float*,const long&,float[],float[],const long&,long&);
RWLAPKDECL void     sorgr2(const long&,const long&,const long&,float*,const long&,float[],float[],long&);
RWLAPKDECL void     sorgrq(const long&,const long&,const long&,float*,const long&,float[],float[],const long&,long&);
RWLAPKDECL void     sorgtr(const char&,const long&,float*,const long&,float[],float[],const long&,long&);
RWLAPKDECL void     sorm2l(const char&,const char&,const long&,const long&,const long&,float*,const long&,float[],float*,const long&,float[],long&);
RWLAPKDECL void     sorm2r(const char&,const char&,const long&,const long&,const long&,float*,const long&,float[],float*,const long&,float[],long&);
RWLAPKDECL void     sormbr(const char&,const char&,const char&,const long&,const long&,const long&,float*,const long&,float[],float*,const long&,float[],const long&,long&);
RWLAPKDECL void     sormhr(const char&,const char&,const long&,const long&,const long&,const long&,float*,const long&,float[],float*,const long&,float[],const long&,long&);
RWLAPKDECL void     sorml2(const char&,const char&,const long&,const long&,const long&,float*,const long&,float[],float*,const long&,float[],long&);
RWLAPKDECL void     sormlq(const char&,const char&,const long&,const long&,const long&,float*,const long&,float[],float*,const long&,float[],const long&,long&);
RWLAPKDECL void     sormql(const char&,const char&,const long&,const long&,const long&,float*,const long&,float[],float*,const long&,float[],const long&,long&);
RWLAPKDECL void     sormqr(const char&,const char&,const long&,const long&,const long&,float*,const long&,float[],float*,const long&,float[],const long&,long&);
RWLAPKDECL void     sormr2(const char&,const char&,const long&,const long&,const long&,float*,const long&,float[],float*,const long&,float[],long&);
RWLAPKDECL void     sormrq(const char&,const char&,const long&,const long&,const long&,float*,const long&,float[],float*,const long&,float[],const long&,long&);
RWLAPKDECL void     sormtr(const char&,const char&,const char&,const long&,const long&,float*,const long&,float[],float*,const long&,float[],const long&,long&);
RWLAPKDECL void     spbcon(const char&,long&,long&,float*,long&,float&,float&,float[],long[],long&);
RWLAPKDECL void     spbequ(const char&,long&,long&,float*,long&,float[],float&,float&,long&);
RWLAPKDECL void     spbrfs(const char&,const long&,const long&,const long&,float*,const long&,float*,const long&,float*,const long&,float*,const long&,float[],float[],float[],long[],long&);
RWLAPKDECL void     spbsv(const char&,const long&,const long&,const long&,float*,const long&,float*,const long&,long&);
RWLAPKDECL void     spbsvx(const char&,const char&,long&,long&,long&,float*,long&,float*,long&,char&,float[],float*,long&,float*,long&,float&,float[],float[],float[],long[],long&);
RWLAPKDECL void     spbtf2(const char&,const long&,const long&,float*,const long&,long&);
RWLAPKDECL void     spbtrf(const char&,const long&,const long&,float*,const long&,long&);
RWLAPKDECL void     spbtrs(const char&,const long&,const long&,const long&,float*,const long&,float*,const long&,long&);
RWLAPKDECL void     spocon(const char&,long&,float*,long&,float&,float&,float[],long[],long&);
RWLAPKDECL void     spoequ(const long&,float*,const long&,float[],float&,float&,long&);
RWLAPKDECL void     sporfs(const char&,const long&,const long&,float*,const long&,float*,const long&,float*,const long&,float*,const long&,float[],float[],float[],long[],long&);
RWLAPKDECL void     sposv(const char&,const long&,const long&,float*,const long&,float*,const long&,long&);
RWLAPKDECL void     sposvx(const char&,const char&,long&,long&,float*,long&,float*,long&,char&,float[],float*,long&,float*,long&,float&,float[],float[],float[],long[],long&);
RWLAPKDECL void     spotf2(const char&,const long&,float*,const long&,long&);
RWLAPKDECL void     spotrf(const char&,const long&,float*,const long&,long&);
RWLAPKDECL void     spotri(const char&,const long&,float*,const long&,long&);
RWLAPKDECL void     spotrs(const char&,const long&,const long&,float*,const long&,float*,const long&,long&);
RWLAPKDECL void     sppcon(const char&,long&,float[],float&,float&,float[],long[],long&);
RWLAPKDECL void     sppequ(const char&,long&,float[],float[],float&,float&,long&);
RWLAPKDECL void     spprfs(const char&,const long&,const long&,float[],float[],float*,const long&,float*,const long&,float[],float[],float[],long[],long&);
RWLAPKDECL void     sppsv(const char&,const long&,const long&,float[],float*,const long&,long&);
RWLAPKDECL void     sppsvx(const char&,const char&,long&,long&,float[],float[],char&,float[],float*,long&,float*,long&,float&,float[],float[],float[],long[],long&);
RWLAPKDECL void     spptrf(const char&,const long&,float[],long&);
RWLAPKDECL void     spptri(const char&,const long&,float[],long&);
RWLAPKDECL void     spptrs(const char&,const long&,const long&,float[],float*,const long&,long&);
RWLAPKDECL void     sptcon(const long&,float[],float[],const float&,float&,float[],long&);
RWLAPKDECL void     spteqr(const char&,const long&,float[],float[],float*,const long&,float[],long&);
RWLAPKDECL void     sptrfs(const long&,const long&,float[],float[],float[],float[],float*,const long&,float*,const long&,float[],float[],float[],long&);
RWLAPKDECL void     sptsv(const long&,const long&,float[],float[],float*,const long&,long&);
RWLAPKDECL void     sptsvx(const char&,long&,long&,float[],float[],float[],float[],float*,long&,float*,long&,float&,float[],float[],float[],long&);
RWLAPKDECL void     spttrf(const long&,float[],float[],long&);
RWLAPKDECL void     spttrs(const long&,const long&,float[],float[],float*,const long&,long&);
RWLAPKDECL void     srscl(const long&,const float&,float[],const long&);
RWLAPKDECL void     ssbev(const char&,const char&,const long&,const long&,float*,const long&,float[],float*,const long&,float[],long&);
RWLAPKDECL void     ssbevx(const char&,const char&,const char&,long&,long&,float*,long&,float*,long&,float&,float&,long&,long&,float&,long&,float[],float*,long&,float[],long[],long[],long&);
RWLAPKDECL void     ssbtrd(const char&,const char&,const long&,const long&,float*,const long&,float[],float[],float*,const long&,float[],long&);
RWLAPKDECL float    ssecnd();
RWLAPKDECL void     sspcon(const char&,long&,float[],long[],float&,float&,float[],long[],long&);
RWLAPKDECL void     sspev(const char&,const char&,const long&,float[],float[],float*,const long&,float[],long&);
RWLAPKDECL void     sspevx(const char&,const char&,const char&,long&,float[],float&,float&,long&,long&,float&,long&,float[],float*,long&,float[],long[],long[],long&);
RWLAPKDECL void     sspgst(const long&,const char&,const long&,float[],float[],long&);
RWLAPKDECL void     sspgv(const long&,const char&,const char&,const long&,float[],float[],float[],float*,const long&,float[],long&);
RWLAPKDECL void     ssprfs(const char&,const long&,const long&,float[],float[],long[],float*,const long&,float*,const long&,float[],float[],float[],long[],long&);
RWLAPKDECL void     sspsv(const char&,const long&,const long&,float[],long[],float*,const long&,long&);
RWLAPKDECL void     sspsvx(const char&,const char&,long&,long&,float[],float[],long[],float*,long&,float*,long&,float&,float[],float[],float[],long[],long&);
RWLAPKDECL void     ssptrd(const char&,const long&,float[],float[],float[],float[],long&);
RWLAPKDECL void     ssptrf(const char&,const long&,float[],long[],long&);
RWLAPKDECL void     ssptri(const char&,const long&,float[],long[],float[],long&);
RWLAPKDECL void     ssptrs(const char&,const long&,const long&,float[],long[],float*,const long&,long&);
RWLAPKDECL void     sstebz(const char&,const char&,const long&,const float&,const float&,const long&,const long&,const float&,float[],float[],long&,long&,float[],long[],long[],float[],long[],long&);
RWLAPKDECL void     sstein(const long&,float[],float[],const long&,float[],long[],long[],float*,const long&,float[],long[],long[],long&);
RWLAPKDECL void     ssteqr(const char&,const long&,float[],float[],float*,const long&,float[],long&);
RWLAPKDECL void     ssterf(const long&,float[],float[],long&);
RWLAPKDECL void     sstev(const char&,const long&,float[],float[],float*,const long&,float[],long&);
RWLAPKDECL void     sstevx(const char&,const char&,long&,float[],float[],float&,float&,long&,long&,float&,long&,float[],float*,long&,float[],long[],long[],long&);
RWLAPKDECL void     ssycon(const char&,long&,float*,long&,long[],float&,float&,float[],long[],long&);
RWLAPKDECL void     ssyev(const char&,const char&,const long&,float*,const long&,float[],float[],const long&,long&);
RWLAPKDECL void     ssyevx(const char&,const char&,const char&,long&,float*,long&,float&,float&,long&,long&,float&,long&,float[],float*,long&,float[],long&,long[],long[],long&);
RWLAPKDECL void     ssygs2(const long&,const char&,const long&,float*,const long&,float*,const long&,long&);
RWLAPKDECL void     ssygst(const long&,const char&,const long&,float*,const long&,float*,const long&,long&);
RWLAPKDECL void     ssygv(const long&,const char&,const char&,const long&,float*,const long&,float*,const long&,float[],float[],const long&,long&);
RWLAPKDECL void     ssyrfs(const char&,const long&,const long&,float*,const long&,float*,const long&,long[],float*,const long&,float*,const long&,float[],float[],float[],long[],long&);
RWLAPKDECL void     ssysv(const char&,const long&,const long&,float*,const long&,long[],float*,const long&,float[],const long&,long&);
RWLAPKDECL void     ssysvx(const char&,const char&,long&,long&,float*,long&,float*,long&,long[],float*,long&,float*,long&,float&,float[],float[],float[],long&,long[],long&);
RWLAPKDECL void     ssytd2(const char&,const long&,float*,const long&,float[],float[],float[],long&);
RWLAPKDECL void     ssytf2(const char&,const long&,float*,const long&,long[],long&);
RWLAPKDECL void     ssytrd(const char&,const long&,float*,const long&,float[],float[],float[],float[],const long&,long&);
RWLAPKDECL void     ssytrf(const char&,const long&,float*,const long&,long[],float[],const long&,long&);
RWLAPKDECL void     ssytri(const char&,const long&,float*,const long&,long[],float[],long&);
RWLAPKDECL void     ssytrs(const char&,const long&,const long&,float*,const long&,long[],float*,const long&,long&);
RWLAPKDECL void     stbcon(const char&,const char&,const char&,long&,long&,float*,long&,float&,float[],long[],long&);
RWLAPKDECL void     stbrfs(const char&,const char&,const char&,const long&,const long&,const long&,float*,const long&,float*,const long&,float*,const long&,float[],float[],float[],long[],long&);
RWLAPKDECL void     stbtrs(const char&,const char&,const char&,const long&,const long&,const long&,float*,const long&,float*,const long&,long&);
RWLAPKDECL void     stpcon(const char&,const char&,const char&,long&,float[],float&,float[],long[],long&);
RWLAPKDECL void     stprfs(const char&,const char&,const char&,const long&,const long&,float[],float*,const long&,float*,const long&,float[],float[],float[],long[],long&);
RWLAPKDECL void     stptri(const char&,const char&,const long&,float[],long&);
RWLAPKDECL void     stptrs(const char&,const char&,const char&,const long&,const long&,float[],float*,const long&,long&);
RWLAPKDECL void     strcon(const char&,const char&,const char&,long&,float*,long&,float&,float[],long[],long&);
RWLAPKDECL void     strevc(const char&,const char&,int[],const long&,float*,const long&,float*,const long&,float*,const long&,const long&,long&,float[],long&);
RWLAPKDECL void     strexc(const char&,const long&,float*,const long&,float*,const long&,long&,long&,float[],long&);
RWLAPKDECL void     strrfs(const char&,const char&,const char&,const long&,const long&,float*,const long&,float*,const long&,float*,const long&,float[],float[],float[],long[],long&);
RWLAPKDECL void     strsen(const char&,const char&,int[],long&,float*,long&,float*,long&,float[],float[],long&,float&,float&,float[],long&,long[],long&,long&);
RWLAPKDECL void     strsna(const char&,const char&,int[],long&,float*,long&,float*,long&,float*,long&,float[],float[],long&,long&,float*,long&,long[],long&);
RWLAPKDECL void     strsyl(const char&,const char&,const long&,const long&,const long&,float*,const long&,float*,const long&,float*,const long&,float&,long&);
RWLAPKDECL void     strti2(const char&,const char&,const long&,float*,const long&,long&);
RWLAPKDECL void     strtri(const char&,const char&,const long&,float*,const long&,long&);
RWLAPKDECL void     strtrs(const char&,const char&,const char&,const long&,const long&,float*,const long&,float*,const long&,long&);
RWLAPKDECL void     stzrqf(const long&,const long&,float*,const long&,float[],long&);
RWLAPKDECL float    szsum1(const long&,FComplex[],const long&);

#endif
