//
// List of InitialFunc classes
//

#include "initfuncs/arc.h"
#include "initfuncs/circle.h"
#include "initfuncs/constant.h"
#include "initfuncs/cup.h"
#include "initfuncs/dbloval.h"
#include "initfuncs/dblrect.h"
#include "initfuncs/diamond.h"
#include "initfuncs/hardsmile.h"
#include "initfuncs/heavifunc.h"
#include "initfuncs/ifuncunion.h"
#include "initfuncs/linearfunc.h"
#include "initfuncs/line.h"
#include "initfuncs/mdisks.h"
#include "initfuncs/msquares.h"
#include "initfuncs/oval.h"
#include "initfuncs/plus2.h"
#include "initfuncs/plus.h"
#include "initfuncs/sine.h"
#include "initfuncs/square.h"
#include "initfuncs/star.h"
#include "initfuncs/wavyfunc.h"
#include "initfuncs/mirroredcubic.h"
